security:
  jwt:
    secret: 'some-super-secret-some-super-secret-some-super-secret'
    expire: 1800
    algorithm: 'HS256'
  auth:
    isAuthzProtectionEnabled: true
    preAuthnUrls:
       - path: "/api/v1/auth/*/login_action"
         method: "POST"
       - path: "/api/v1/auth/*/authz_client"
         method: "POST"
       - path: "/api/v1/auth/*/exchange_token"
         method: "POST"
       - path: "/api/v1/oidc/*/.well-known/openid-configuration"
         method: "GET"

config:
  dimension:
    name: "super"
    displayName: "God-Dimension"
  client:
    name: "master"
    secret: "0a5f4360-ae03-4f8a-8020-189a934a4e05-9873e4ca-403b-4ee6-99b3-2c6e7b7e380d"
    redirectUri: "http://localhost:8085/**"
  admin:
    firstName: "Admin"
    lastName: "User"
    userName: "admin"
    email: "user@email.com"
    password: "password"

cache:
  type: "INF-EMB"
  memory: 1000
  lifespan: 300 # in seconds
  deleteOnRetrieve: false
    